# Generated by Django 4.0.6 on 2023-02-13 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('childid', models.IntegerField(primary_key=True, serialize=False)),
                ('childname', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField(max_length=10)),
                ('fathername', models.CharField(max_length=10)),
                ('mothername', models.CharField(max_length=10)),
                ('birthplace', models.CharField(max_length=10)),
                ('registeredon', models.CharField(max_length=10)),
                ('birthproof', models.FileField(null=True, upload_to='birthproof/')),
            ],
        ),
        migrations.CreateModel(
            name='Grampanchayat',
            fields=[
                ('gramid', models.IntegerField(primary_key=True, serialize=False)),
                ('gramname', models.CharField(max_length=50)),
                ('gramaddress', models.TextField(max_length=100)),
                ('gramemail', models.EmailField(max_length=254)),
                ('gramcontact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('houseid', models.IntegerField(primary_key=True, serialize=False)),
                ('vibhag', models.CharField(max_length=50)),
                ('vadi', models.CharField(max_length=50)),
                ('housetype', models.CharField(max_length=50)),
                ('housedimension', models.IntegerField()),
                ('ownername', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Housetaxinfo',
            fields=[
                ('housetypeid', models.IntegerField(primary_key=True, serialize=False)),
                ('housetype', models.CharField(max_length=50)),
                ('hosetaxrate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spotid', models.IntegerField(primary_key=True, serialize=False)),
                ('spottype', models.CharField(max_length=50)),
                ('spotname', models.TextField(max_length=100)),
                ('spotlocation', models.TextField(max_length=100)),
                ('spotimage', models.FileField(null=True, upload_to='gramadmin/')),
                ('spotdescription', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gramadmin',
            fields=[
                ('gramadminid', models.IntegerField(primary_key=True, serialize=False)),
                ('gramadminmobno', models.CharField(max_length=10)),
                ('gramadminphoto', models.FileField(null=True, upload_to='gramadmin/')),
                ('grampanchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramapp.grampanchayat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
